export interface TokenizedStock {
  id: string;
  ticker: string;
  name: string;
  mintAddress: string;
  decimals: number;
  sector: "AI & Chips" | "Big Tech" | "EV & Energy" | "Crypto Equity" | "Index / ETF" | "Media & Retail" | "Cloud & Defense";
  basePrice: number;
  change24h: number;
  marketCap: string;
  peRatio?: number;
  volume24h: string;
  buySentimentPct: number; // e.g. 88%
  whyMoving: string;
  catalystPills: string[];
  color: string;
  gradient: string;
  underlyingAsset: string;
  isDevnetMock: boolean;
  isToken2022?: boolean;
}

export const DUSD_MINT_ADDRESS =
  process.env.NEXT_PUBLIC_DUSD_MINT || "Fein1Aykk2ymzUEzsio8mZ1oKCyBHzMPiH8gxBipkpQV";

export const MAINNET_USDC_MINT = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v";

export const SESSION_DELEGATE_PUBKEY =
  process.env.NEXT_PUBLIC_SOLANA_SESSION_DELEGATE || "4QipWeecZ1y9om6wRJ5XDabf5QHQfJJGpqPoUVgHh4W4";

/**
 * Devnet Synthetic Stock Catalog (SPL Legacy Mints with sponsored gas & dUSD swaps)
 */
export const DEVNET_MOCK_STOCKS: TokenizedStock[] = [
  {
    id: "nvda",
    ticker: "NVDA",
    name: "NVIDIA Corporation",
    mintAddress: "72Mkr9AFqpbF3pdQX8w6S6nEBBFBjevRdtHNNQPcTKva",
    decimals: 6,
    sector: "AI & Chips",
    basePrice: 128.5,
    change24h: 4.82,
    marketCap: "$3.15T",
    peRatio: 52.4,
    volume24h: "$1.4B",
    buySentimentPct: 88,
    whyMoving: "Blackwell Ultra GPU ramp accelerates; enterprise datacenter revenue projected to grow 40% YoY.",
    catalystPills: ["AI Hardware", "Datacenter Supercycle", "Margin Expansion"],
    color: "#76B900",
    gradient: "from-[#76B900]/20 via-[#76B900]/5 to-transparent",
    underlyingAsset: "NASDAQ:NVDA",
    isDevnetMock: true,
  },
  {
    id: "tsla",
    ticker: "TSLA",
    name: "Tesla Inc",
    mintAddress: "HSH2futXhFnp7oUWkoAeDeb8xia47RQtfvGPFEqmhEj1",
    decimals: 6,
    sector: "EV & Energy",
    basePrice: 242.8,
    change24h: 3.15,
    marketCap: "$770B",
    peRatio: 64.2,
    volume24h: "$980M",
    buySentimentPct: 76,
    whyMoving: "Cybercab Robotaxi autonomous network roadmap unveiled + energy storage deployment records.",
    catalystPills: ["Robotaxi Fleet", "Megapack Energy", "FSD Autonomous"],
    color: "#E82127",
    gradient: "from-[#E82127]/20 via-[#E82127]/5 to-transparent",
    underlyingAsset: "NASDAQ:TSLA",
    isDevnetMock: true,
  },
  {
    id: "mstr",
    ticker: "MSTR",
    name: "MicroStrategy Inc",
    mintAddress: "A4F73hvH1AmHWJZNQB2uVuL1aPmPrHqZsibiaQ6iM4Ph",
    decimals: 6,
    sector: "Crypto Equity",
    basePrice: 145.2,
    change24h: 7.64,
    marketCap: "$28.6B",
    volume24h: "$640M",
    buySentimentPct: 91,
    whyMoving: "Acquired additional 7,420 BTC; institutional treasury model reaches peak NAV multiple.",
    catalystPills: ["Bitcoin Treasury", "High-Beta Proxy", "Capital Formation"],
    color: "#D03027",
    gradient: "from-[#D03027]/20 via-[#D03027]/5 to-transparent",
    underlyingAsset: "NASDAQ:MSTR",
    isDevnetMock: true,
  },
  {
    id: "coin",
    ticker: "COIN",
    name: "Coinbase Global",
    mintAddress: "92befgELFFk8kWUy2TgYShbSJL7vjygGRuLk6MPRv9au",
    decimals: 6,
    sector: "Crypto Equity",
    basePrice: 218.4,
    change24h: 5.31,
    marketCap: "$53.8B",
    peRatio: 38.1,
    volume24h: "$510M",
    buySentimentPct: 83,
    whyMoving: "Base Layer-2 ecosystem fees surge 210% alongside global institutional custody expansion.",
    catalystPills: ["Base Ecosystem", "ETF Custody", "Derivatives Volume"],
    color: "#0052FF",
    gradient: "from-[#0052FF]/20 via-[#0052FF]/5 to-transparent",
    underlyingAsset: "NASDAQ:COIN",
    isDevnetMock: true,
  },
  {
    id: "aapl",
    ticker: "AAPL",
    name: "Apple Inc",
    mintAddress: "AsXwg3Qpz5RHMCR2hPFoV91KMsd5uq81KHdk82Cz4xNZ",
    decimals: 6,
    sector: "Big Tech",
    basePrice: 226.7,
    change24h: 1.12,
    marketCap: "$3.45T",
    peRatio: 33.8,
    volume24h: "$820M",
    buySentimentPct: 71,
    whyMoving: "Apple Intelligence features rolled out globally, accelerating multi-year device upgrade cycles.",
    catalystPills: ["Apple Intelligence", "Services Revenue", "$110B Buyback"],
    color: "#A2AAAD",
    gradient: "from-slate-400/20 via-slate-400/5 to-transparent",
    underlyingAsset: "NASDAQ:AAPL",
    isDevnetMock: true,
  },
  {
    id: "msft",
    ticker: "MSFT",
    name: "Microsoft Corp",
    mintAddress: "Cfh7o52E83LzGhECguBymxKCH6f6BRU5Gt5Qv4VH17i6",
    decimals: 6,
    sector: "Big Tech",
    basePrice: 428.6,
    change24h: 2.05,
    marketCap: "$3.18T",
    peRatio: 35.6,
    volume24h: "$730M",
    buySentimentPct: 79,
    whyMoving: "Azure Cloud AI customer base expands 60% YoY; Copilot enterprise adoption accelerates.",
    catalystPills: ["Azure AI Infrastructure", "Copilot Subscriptions", "OpenAI Partnership"],
    color: "#00A4EF",
    gradient: "from-[#00A4EF]/20 via-[#00A4EF]/5 to-transparent",
    underlyingAsset: "NASDAQ:MSFT",
    isDevnetMock: true,
  },
  {
    id: "amzn",
    ticker: "AMZN",
    name: "Amazon.com Inc",
    mintAddress: "BDyGxLJ7B7e2umTKyVNY1JoSH85pKASQ1cG3QvaBWBa3",
    decimals: 6,
    sector: "Big Tech",
    basePrice: 186.4,
    change24h: 1.84,
    marketCap: "$1.94T",
    peRatio: 42.1,
    volume24h: "$670M",
    buySentimentPct: 74,
    whyMoving: "AWS generative AI annualized run-rate hits multibillion milestone; retail margins widen.",
    catalystPills: ["AWS Growth", "High-Margin Ads", "Logistics Automation"],
    color: "#FF9900",
    gradient: "from-[#FF9900]/20 via-[#FF9900]/5 to-transparent",
    underlyingAsset: "NASDAQ:AMZN",
    isDevnetMock: true,
  },
  {
    id: "googl",
    ticker: "GOOGL",
    name: "Alphabet Inc",
    mintAddress: "Fzr3zscz1MVFG2CveghfskjJtPfQcMucVH3HvqejSid1",
    decimals: 6,
    sector: "Big Tech",
    basePrice: 164.8,
    change24h: -0.45,
    marketCap: "$2.05T",
    peRatio: 24.2,
    volume24h: "$580M",
    buySentimentPct: 68,
    whyMoving: "Gemini AI multimodal capabilities embedded across Google Search, Workspace, and Cloud.",
    catalystPills: ["Gemini 1.5 Pro", "Search Leadership", "YouTube Monetization"],
    color: "#4285F4",
    gradient: "from-[#4285F4]/20 via-[#4285F4]/5 to-transparent",
    underlyingAsset: "NASDAQ:GOOGL",
    isDevnetMock: true,
  },
  {
    id: "amd",
    ticker: "AMD",
    name: "Advanced Micro Devices",
    mintAddress: "BJGg2TbmTsK5X7grHi2paUfvGTgJ3aWi3BQ8RC6ttRtN",
    decimals: 6,
    sector: "AI & Chips",
    basePrice: 156.9,
    change24h: 3.89,
    marketCap: "$254B",
    peRatio: 48.7,
    volume24h: "$430M",
    buySentimentPct: 80,
    whyMoving: "MI300X AI GPU deployment expands across tier-1 hyperscalers; Zen 5 server market gains.",
    catalystPills: ["MI300X Accelerator", "Server CPU Gains", "AI PC Chips"],
    color: "#ED1C24",
    gradient: "from-[#ED1C24]/20 via-[#ED1C24]/5 to-transparent",
    underlyingAsset: "NASDAQ:AMD",
    isDevnetMock: true,
  },
  {
    id: "spy",
    ticker: "SPY",
    name: "SPDR S&P 500 ETF",
    mintAddress: "HWXhDZec1kmUGu8yfUPZDGTwvsAXzSmBUmba9ShdN9Qg",
    decimals: 6,
    sector: "Index / ETF",
    basePrice: 562.3,
    change24h: 0.85,
    marketCap: "$580B",
    volume24h: "$2.1B",
    buySentimentPct: 85,
    whyMoving: "Broad market rally supported by macroeconomic resilience and tech earnings leadership.",
    catalystPills: ["Index Benchmark", "Macro Tailwinds", "US Corporate Strength"],
    color: "#14F195",
    gradient: "from-[#14F195]/20 via-[#14F195]/5 to-transparent",
    underlyingAsset: "NYSEARCA:SPY",
    isDevnetMock: true,
  },
  {
    id: "nflx",
    ticker: "NFLX",
    name: "Netflix Inc",
    mintAddress: "VuVvFJjNg6iN9XYKrcFn8RTVPrEo9MKUxmtN8xipNDe",
    decimals: 6,
    sector: "Media & Retail",
    basePrice: 698.5,
    change24h: 2.76,
    marketCap: "$299B",
    peRatio: 41.2,
    volume24h: "$320M",
    buySentimentPct: 77,
    whyMoving: "Ad-supported plan hits 40M active subscribers; live entertainment and sports streaming growth.",
    catalystPills: ["Ad Tier Scale", "Live Events (NFL/WWE)", "Operating Margin +28%"],
    color: "#E50914",
    gradient: "from-[#E50914]/20 via-[#E50914]/5 to-transparent",
    underlyingAsset: "NASDAQ:NFLX",
    isDevnetMock: true,
  },
  {
    id: "baba",
    ticker: "BABA",
    name: "Alibaba Group",
    mintAddress: "Hf6HnbNogBuGQiD6uctxFKsttxsAfF13iSQbEVv1zrYe",
    decimals: 6,
    sector: "Big Tech",
    basePrice: 87.2,
    change24h: 4.12,
    marketCap: "$206B",
    peRatio: 12.8,
    volume24h: "$410M",
    buySentimentPct: 69,
    whyMoving: "Cloud intelligence and international commerce deliver double-digit growth; aggressive buybacks.",
    catalystPills: ["Cloud AI Growth", "Deep Value P/E", "Share Repurchase"],
    color: "#FF6A00",
    gradient: "from-[#FF6A00]/20 via-[#FF6A00]/5 to-transparent",
    underlyingAsset: "NYSE:BABA",
    isDevnetMock: true,
  },
];

/**
 * Official Verified xStocks Catalog on Solana Mainnet-Beta (SPL Token-2022)
 * Source: Solana Official Case Study (solana.com/news/case-study-xstocks) & Raydium DEX Pools
 */
export const MAINNET_XSTOCKS: TokenizedStock[] = [
  {
    id: "nvdax",
    ticker: "NVDAx",
    name: "NVIDIA Corporation (xStock)",
    mintAddress: "Xsc9qvGR1efVDFGLrVsmkzv3qi45LTBjeUKSPmx9qEh",
    decimals: 8,
    sector: "AI & Chips",
    basePrice: 212.71,
    change24h: 4.82,
    marketCap: "$3.15T",
    peRatio: 52.4,
    volume24h: "$1.65M",
    buySentimentPct: 89,
    whyMoving: "1:1 Backed real equity share in custody. Blackwell Ultra datacenter demand drives record Raydium DEX volume.",
    catalystPills: ["Real 1:1 Backed", "Raydium $2.1M Pool", "Token-2022"],
    color: "#76B900",
    gradient: "from-[#76B900]/20 via-[#76B900]/5 to-transparent",
    underlyingAsset: "NASDAQ:NVDA",
    isDevnetMock: false,
    isToken2022: true,
  },
  {
    id: "tslax",
    ticker: "TSLAx",
    name: "Tesla Inc (xStock)",
    mintAddress: "XsDoVfqeBukxuZHWhdvWHBhgEHjGNst4MLodqsJHzoB",
    decimals: 8,
    sector: "EV & Energy",
    basePrice: 360.16,
    change24h: 3.15,
    marketCap: "$770B",
    peRatio: 64.2,
    volume24h: "$1.66M",
    buySentimentPct: 78,
    whyMoving: "1:1 Backed real equity share. Cybercab Robotaxi roadmap and energy storage expansion.",
    catalystPills: ["Real 1:1 Backed", "Raydium $2.1M Pool", "Token-2022"],
    color: "#E82127",
    gradient: "from-[#E82127]/20 via-[#E82127]/5 to-transparent",
    underlyingAsset: "NASDAQ:TSLA",
    isDevnetMock: false,
    isToken2022: true,
  },
  {
    id: "spyx",
    ticker: "SPYx",
    name: "SPDR S&P 500 ETF (xStock)",
    mintAddress: "XsoCS1TfEyfFhfvj8EtZ528L3CaKBDBRqRapnBbDF2W",
    decimals: 8,
    sector: "Index / ETF",
    basePrice: 766.96,
    change24h: 0.85,
    marketCap: "$580B",
    volume24h: "$5.05M",
    buySentimentPct: 86,
    whyMoving: "1:1 Backed S&P 500 index exposure on Solana with $2.6M+ Raydium liquidity pool.",
    catalystPills: ["Real 1:1 Backed", "Raydium $2.6M Pool", "Token-2022"],
    color: "#14F195",
    gradient: "from-[#14F195]/20 via-[#14F195]/5 to-transparent",
    underlyingAsset: "NYSEARCA:SPY",
    isDevnetMock: false,
    isToken2022: true,
  },
  {
    id: "mstrx",
    ticker: "MSTRx",
    name: "MicroStrategy Inc (xStock)",
    mintAddress: "XsP7xzNPvEHS1m6qfanPUGjNmdnmsLKEoNAnHjdxxyZ",
    decimals: 8,
    sector: "Crypto Equity",
    basePrice: 135.88,
    change24h: 7.64,
    marketCap: "$28.6B",
    volume24h: "$491K",
    buySentimentPct: 92,
    whyMoving: "1:1 Backed Bitcoin treasury equity. High-beta exposure directly tradable via Solana Raydium pools.",
    catalystPills: ["Real 1:1 Backed", "Raydium $736K Pool", "Token-2022"],
    color: "#D03027",
    gradient: "from-[#D03027]/20 via-[#D03027]/5 to-transparent",
    underlyingAsset: "NASDAQ:MSTR",
    isDevnetMock: false,
    isToken2022: true,
  },
  {
    id: "aaplx",
    ticker: "AAPLx",
    name: "Apple Inc (xStock)",
    mintAddress: "XsbEhLAtcf6HdfpFZ5xEMdqW8nfAvcsP5bdudRLJzJp",
    decimals: 8,
    sector: "Big Tech",
    basePrice: 335.34,
    change24h: 1.12,
    marketCap: "$3.45T",
    peRatio: 33.8,
    volume24h: "$464K",
    buySentimentPct: 73,
    whyMoving: "1:1 Backed Apple share. Apple Intelligence rollout and services margin expansion.",
    catalystPills: ["Real 1:1 Backed", "Raydium $361K Pool", "Token-2022"],
    color: "#A2AAAD",
    gradient: "from-slate-400/20 via-slate-400/5 to-transparent",
    underlyingAsset: "NASDAQ:AAPL",
    isDevnetMock: false,
    isToken2022: true,
  },
  {
    id: "googlx",
    ticker: "GOOGLx",
    name: "Alphabet Inc (xStock)",
    mintAddress: "XsCPL9dNWBMvFtTmwcCA5v3xWPSMEBCszbQdiLLq6aN",
    decimals: 8,
    sector: "Big Tech",
    basePrice: 347.26,
    change24h: -0.45,
    marketCap: "$2.05T",
    peRatio: 24.2,
    volume24h: "$502K",
    buySentimentPct: 70,
    whyMoving: "1:1 Backed Google share. Gemini AI multimodal search integration and Cloud acceleration.",
    catalystPills: ["Real 1:1 Backed", "Raydium $412K Pool", "Token-2022"],
    color: "#4285F4",
    gradient: "from-[#4285F4]/20 via-[#4285F4]/5 to-transparent",
    underlyingAsset: "NASDAQ:GOOGL",
    isDevnetMock: false,
    isToken2022: true,
  },
  {
    id: "amznx",
    ticker: "AMZNx",
    name: "Amazon.com Inc (xStock)",
    mintAddress: "Xs3eBt7uRfJX8QUs4suhyU8p2M6DoUDrJyWBa8LLZsg",
    decimals: 8,
    sector: "Big Tech",
    basePrice: 186.4,
    change24h: 1.84,
    marketCap: "$1.94T",
    peRatio: 42.1,
    volume24h: "$380K",
    buySentimentPct: 75,
    whyMoving: "1:1 Backed Amazon share. AWS cloud profitability and generative AI infrastructure expansion.",
    catalystPills: ["Real 1:1 Backed", "Raydium DEX", "Token-2022"],
    color: "#FF9900",
    gradient: "from-[#FF9900]/20 via-[#FF9900]/5 to-transparent",
    underlyingAsset: "NASDAQ:AMZN",
    isDevnetMock: false,
    isToken2022: true,
  },
  {
    id: "metax",
    ticker: "METAx",
    name: "Meta Platforms Inc (xStock)",
    mintAddress: "Xsa62P5mvPszXL1krVUnU5ar38bBSVcWAB6fmPCo5Zu",
    decimals: 8,
    sector: "Big Tech",
    basePrice: 512.4,
    change24h: 2.65,
    marketCap: "$1.30T",
    peRatio: 26.5,
    volume24h: "$420K",
    buySentimentPct: 82,
    whyMoving: "1:1 Backed Meta equity. Llama AI open models and ad impression monetization strength.",
    catalystPills: ["Real 1:1 Backed", "Raydium DEX", "Token-2022"],
    color: "#0668E1",
    gradient: "from-[#0668E1]/20 via-[#0668E1]/5 to-transparent",
    underlyingAsset: "NASDAQ:META",
    isDevnetMock: false,
    isToken2022: true,
  },
  {
    id: "msftx",
    ticker: "MSFTx",
    name: "Microsoft Corp (xStock)",
    mintAddress: "XspzcW1PRtgf6Wj92HCiZdjzKCyFekVD8P5Ueh3dRMX",
    decimals: 8,
    sector: "Big Tech",
    basePrice: 428.6,
    change24h: 2.05,
    marketCap: "$3.18T",
    peRatio: 35.6,
    volume24h: "$510K",
    buySentimentPct: 80,
    whyMoving: "1:1 Backed Microsoft share. Azure enterprise AI expansion and Office Copilot adoption.",
    catalystPills: ["Real 1:1 Backed", "Raydium DEX", "Token-2022"],
    color: "#00A4EF",
    gradient: "from-[#00A4EF]/20 via-[#00A4EF]/5 to-transparent",
    underlyingAsset: "NASDAQ:MSFT",
    isDevnetMock: false,
    isToken2022: true,
  },
  {
    id: "coinx",
    ticker: "COINx",
    name: "Coinbase Global (xStock)",
    mintAddress: "Xs7ZdzSHLU9ftNJsii5fCeJhoRWSC32SQGzGQtePxNu",
    decimals: 8,
    sector: "Crypto Equity",
    basePrice: 218.4,
    change24h: 5.31,
    marketCap: "$53.8B",
    peRatio: 38.1,
    volume24h: "$620K",
    buySentimentPct: 85,
    whyMoving: "1:1 Backed Coinbase equity. Base L2 revenue expansion and global ETF custody leadership.",
    catalystPills: ["Real 1:1 Backed", "Raydium DEX", "Token-2022"],
    color: "#0052FF",
    gradient: "from-[#0052FF]/20 via-[#0052FF]/5 to-transparent",
    underlyingAsset: "NASDAQ:COIN",
    isDevnetMock: false,
    isToken2022: true,
  },
];

export const VERIFIED_TOKENIZED_STOCKS = DEVNET_MOCK_STOCKS;

export function getStocksForNetwork(network: "devnet" | "mainnet"): TokenizedStock[] {
  return network === "mainnet" ? MAINNET_XSTOCKS : DEVNET_MOCK_STOCKS;
}

export function getCurrencyForNetwork(network: "devnet" | "mainnet"): {
  symbol: string;
  name: string;
  mintAddress: string;
  decimals: number;
} {
  if (network === "mainnet") {
    return {
      symbol: "USDC",
      name: "USD Coin",
      mintAddress: MAINNET_USDC_MINT,
      decimals: 6,
    };
  }
  return {
    symbol: "dUSD",
    name: "Devnet Dollar",
    mintAddress: DUSD_MINT_ADDRESS,
    decimals: 6,
  };
}
